[package]
authors = ["The Rust Project Developers"]
name = "rustc_data_structures"
version = "0.0.0"

[lib]
name = "rustc_data_structures"
path = "lib.rs"
crate-type = ["dylib"]

[dependencies]
log = "0.3"
serialize = { path = "../libserialize" }
cfg-if = "0.1.2"
lazy_static = "0.2.10"

[dependencies.parking_lot]
version = "0.5"
features = ["nightly", "owning_ref"]